// Code generated by Slice Machine. DO NOT EDIT.

import Certificate from './Certificate/index.svelte';
import Hero from './Hero/index.svelte';
import Project from './Project/index.svelte';
import RichText from './RichText/index.svelte';
import Showcase from './Showcase/index.svelte';

export const components = {
	certificate: Certificate,
	hero: Hero,
	project: Project,
	rich_text: RichText,
	showcase: Showcase
};
